# netlify.toml
# elektrolurch.net
# 15.04.2026

[[redirects]]
  from = "https://42.elektrolurch.net/"
  to = "https://blog.elektrolurch.net/memes/42/"
  status = 301
  force = true

[[redirects]]
  from = "https://42.elektrolurch.net/*"
  to = "https://blog.elektrolurch.net/memes/42/:splat"
  status = 301
  force = true
